### ISSUE TITLE
doesn't work with internal ELB

### ISSUE THREAD

**Issue by itajaja** [wearemolecule/route53-kubernetes#10]
internal ELBs' DNS is prepended by `internal-`, [this line](https://github.com/wearemolecule/route53-kubernetes/blob/master/service_listener.go#L172), that should retrieve the ELB name, doesn't work with that naming schema, because it returns `internal` as the dns name

**Comment by dgershman** [comment]
+1 This feature

**Comment by itajaja** [comment]
I made an attempt #13

**Comment by iterion** [comment]
`v1.1.4` has been tagged and an image built, please test and reopen this issue if needed.
