### ISSUE TITLE
Support multiple domains per service

### ISSUE THREAD

**Issue by kichik** [wearemolecule/route53-kubernetes#16]

**Comment by iterion** [comment]
Good idea, any thoughts on how you'd like to specify multiple domains? Comma separated?

**Comment by kichik** [comment]
The way I have it right now in my separate script is comma separated. I think the "kubernetes way" is an actual list, but I don't know if that's actually supported under annotations. If it's not, comma separation would definitely be better than the alternative of `domain0`, `domain1`, etc.

**Comment by alexdej** [comment]
One caveat to this: if you're terminating TLS in ELB then you'll still need multiple services so that each domain gets the ELB with matching cert.

**Comment by kichik** [comment]
I used a certificate with multiple alternative names for that. Let's Encrypt supports that. In my case it was nginx that terminated TLS, but I'm sure ELB supports that too.

**Comment by iterion** [comment]
Support was merged in #25. New tag coming shortly.
