### ISSUE TITLE
Support Service Account

### ISSUE THREAD

**Issue by Camsteack** [wearemolecule/route53-kubernetes#18]
Support service account to talk to Kubernetes API.

**Comment by iterion** [comment]
Agree this would be useful. Thanks for opening the issue.

**Comment by Camsteack** [comment]
I am going to try to see if I can contribute to something as I would really like that feature but I am really green to GO and the Kubernetes SDK 😄

**Comment by iterion** [comment]
That'd be fantastic, always open to questions if you have any. Good luck!

Also, if you'd like to pair sometime once you've started something I'm open to that as well.

**Comment by iterion** [comment]
Support for service accounts was added via #21. That release is tagged at v1.1.5 and a docker image is available at that same tag.
