### ISSUE TITLE
Handle internal and external HostedZones with the same name

### ISSUE THREAD

**Issue by iterion** [wearemolecule/route53-kubernetes#29]

**Comment by dosullivan** [comment]
I have added a basic patch on my fork that defaults to using the private zone when both public and private zones are present, as that is useful in my team's use case:
https://github.com/dosullivan/route53-kubernetes/commit/f23f8211e95d2e7530ba4e2d0bb95ec86344f4cc

Not sure if this would be helpful to others, but I'd be glad to make a pull request if so. Perhaps this could be used as a basis for other work on this.
