### ISSUE TITLE
Optionally include the namespace in the hostname, perhaps via template

### ISSUE THREAD

**Issue by timbunce** [wearemolecule/route53-kubernetes#30]
Having a single hardcoded hostname causes problems for us.
We want to be able to reuse a single service definition in different namespaces and clusters.
The kubernetes/kubernetes#21397 issue suggests a format for dynamically defining route53 hostnames using the format `[service-name]-[namespace]-[hosted-zone].[zone]`. That would work for us but is very rigid.

If the `domainName` annotation supported template fields then we'd be able to express our needs as something like: `domainName: "{{.service}}-{{.namespace}}.mydomain.com"`.

(I think that would be simple to implement using text/template. I'd offer a PR but I've not done any Go programming yet.)

**Comment by iterion** [comment]
Thanks for the issue. I think something like this could be useful for us as well. We currently pass our service definitions through a template engine that then fills in the domain name for us in cases where the service is duplicated. Then we just pipe the results of that into `kubectl create`.

**Comment by timbunce** [comment]
Yes, external templating is our fallback approach also, but it's cumbersome.

**Comment by alexdej** [comment]
FWIW my solution to this was to remove the annotation from the service definition and add it as a separate step in my creation script. Something like the following (assume `ns` is like `"staging"`) :

```
kubectl --namespace=$ns create -f services/api.json
kubectl --namespace=$ns annotate service api domainName="api-$ns.bar.com"
```

**Comment by timbunce** [comment]
Nice approach. Thanks @alexdej. (Though tricky to apply to a whole directory of services.)
