### ISSUE TITLE
Add support for Ingress

### ISSUE THREAD

**Issue by jaygorrell** [wearemolecule/route53-kubernetes#32]
Would it be within scope of this project to support Ingress resources?

I'd love to use this project but in my setup I have a single `LoadBalancer` service that needs multiple declared DNS entries pointing to it for use with Ingress -- each of these would be bound to an `Ingress` resource. Ideally, I'd just annotate the `Ingress` resource with a targeted `LoadBalancer` service or something along those lines.

**Comment by iterion** [comment]
Possibly, I haven't looked too deeply at ingress resources. I'll do some
research and see how we might be able to use them.

**Comment by goruha** [comment]
Check this fork they already implemented ingress
@gianrubio
https://github.com/gianrubio/route53-kubernetes

**Comment by ideahitme** [comment]
@jaygorrell it is already supported in Mate https://github.com/zalando-incubator/mate

**Comment by iterion** [comment]
Ingress is supported now in https://github.com/kubernetes-incubator/external-dns which is the recommended tool.
