### ISSUE TITLE
IAM permission troubles

### ISSUE THREAD

**Issue by andrewwatson** [wearemolecule/route53-kubernetes#34]
I created an IAM policy like so:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "route53:ListHostedZonesByName",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "elasticloadbalancing:DescribeLoadBalancers",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "route53:ChangeResourceRecordSets",
            "Resource": "*"
        }
    ]
}
```

and associated it with the same use that was used to create my kubernetes cluster.

However, when starting up the deployment of this application I get errors about IAM permissions:

```
service_listener.go:145] Couldn't get zone ID: Could not describe load balancer: AccessDenied: User: arn:aws:sts::201248577332:assumed-role/kubernetes-minion/i-704a92de is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers
```

**Comment by iterion** [comment]
Double check that your IAM role named kubernetes-minion has been assigned the policy you created above. Things should start working then.

**Comment by andrewwatson** [comment]
ok, i created a new cluster with kops 1.4.1, k8s 1.4.6 on AWS and I still get the same error.  How can I go about troubleshooting this issue to find out for sure why it's not getting the right permissions from IAM?

Thanks!

**Comment by iterion** [comment]
With kops and the default setup it should have created an IAM role named `nodes.<name-of-your-cluster>`. So something like `nodes.kubernetes.example.com`.

For kops, I simply add another policy to that role specifying the same permissions you gave above. For me, to troubleshoot in the past it was a matter looking at the logs from `route53-kubernetes` and then comparing that to the setup and adding the necessary permissions.

**Comment by iterion** [comment]
Also, it's important to note that sometimes IAM permissions can take a little bit to propogate, so make sure to give everything a few minutes to settle before trying something new.
