### ISSUE TITLE
Should delete old record when deleting or updating service

### ISSUE THREAD

**Issue by justinclayton** [wearemolecule/route53-kubernetes#35]
I realize this would require starting to maintain state, which is a larger change.

**Comment by someword** [comment]
@justinclayton I was pondering this myself a few minutes ago.   

What about using a route53 txt records as the state?   This also allows us to differentiate between records we manage and ones managed by another system.

The lifecycle would be something like this.

1.  route53-kubernetes pod sees new service with appropriate annotations/labels and creates new dns record of type A that points to the ELB.   Additionally a txt record is created with the same name as the A record. 
2.  Periodically (daily?) route53-kubernetes would get the txt records from the hosted zones and compare the name to the domainName annotation on each service.  If a txt record does not have a matching service then both the A record and txt record are removed.

Another more vague idea would be to watch the services events and when a service get's deleted check to see if an corresponding route53 entry exists and delete it.  This assumes that after the service delete event you can still get the the service details to find out what the value of domainName was.

**Comment by ideahitme** [comment]
@someword that is similar to what https://github.com/zalando-incubator/mate is doing.

**Comment by someword** [comment]
@ideahitme 
Thanks for the pointer - i'll have to check that project out.

**Comment by iterion** [comment]
https://github.com/kubernetes-incubator/external-dns is the recommended alternative and offers this functionality. It also has a compatibility mode for route53-kubernetes.
