### ISSUE TITLE
Make project work from outside of AWS

### ISSUE THREAD

**Issue by jomagam** [wearemolecule/route53-kubernetes#43]
I would like to throw out the idea of making things work from a cluster that resides outside of AWS. This would be useful for organizations that have a multi-cloud setup where all DNS is in Route53.

The technical solution could involve having the AWS credentials as a secret. Load balancers in other services, like Azure, have a fixed IP address rather than a DNS name like AWS, so they would need the appropriate record type in Route53.

Thoughts ?

**Comment by iterion** [comment]
Thanks for the idea, unfortunately I think that's probably out of the scope of this project. Further, there are plans in the works by the kubernetes team to implement their own cross platform solution for this problem. The idea is to incorporate some of the solutions found here and from other related projects. The proposal can be found here: https://docs.google.com/document/d/1qaTGTLpPRMqMFZo17J169BsqIfY652Miqc_xXVCYm1Y/edit#heading=h.ptnywy975adq

As such, I probably won't be accepting any major changes like the above into this project.

**Comment by jomagam** [comment]
Thanks; I'll be following that proposal closely.
