### ISSUE TITLE
Use only hostname of FQDN

### ISSUE THREAD

**Issue by jangrewe** [wearemolecule/route53-kubernetes#46]
I just found your project and was very excited to try it out, unfortunately it seems to always use just the domain as its base zone, instead of only using the hostname from the FQDN and using the rest as the zone.
So in my example i have `traefik.k8s.int.example.com`, the hosted zone being `k8s.int.example.com`, but it tries to use the zone `example.com`.

I guess only using the hostname is a safe bet. Otherwise maybe get the hosted zones from Route53 and try to match the record to the zone that contains "the longest part" of the FQDN?

**Comment by iterion** [comment]
@jangrewe That's surprising. We should be finding the most specific zone for a given FQDN. See the code @ https://github.com/wearemolecule/route53-kubernetes/blob/master/service_listener.go#L198

We check all zones and keep the one whose matched length is the longest. I'm not sure what's happening here. Could you take a look at the code and help me understand why it's failing for you in this case? I'd love to try to find a fix.

**Comment by jangrewe** [comment]
@iterion You are absolutely right, that was my fault. I checked my my IAM policies again, and the instances only had the permission `ListHostedZones`, not `ListHostedZonesByName`. I've added that permission, now it's working flawlessly. Thank you! =)

**Comment by foobarto** [comment]
I would vote for re-opening this as the request is still valid. It's a good practice to avoid deployment specific details in the yaml definition. That's why we have things like Persistent Volume and Storage Class which can be handled separately from Persistent Volume Claims. This provides a way to separate infrastructure from application neatly. 
It also greatly helps in scenarios where you may be doing blue/green upgrades of whole kubernetes clusters and not having to worry about cluster specific details that have to be updated for every service.

**Comment by jangrewe** [comment]
That's true, i still haven't gotten to the point where i start to worry about how to get around using different values for different environments, short of replacing those values on the fly during deployment.

**Comment by iterion** [comment]
I'm sorry, how is any of this related?

**Comment by foobarto** [comment]
Not exactly related to the issue you've encountered but useful as a feature :)

**Comment by jangrewe** [comment]
Well, not directly related to my issue, but at least the issue title is still fitting :)
I'm happy to close this issue, though, if you prefer @foobarto or me to open a new one as a feature request?

**Comment by foobarto** [comment]
Hmm to reduce confusion perhaps a new issue would indeed fit better as feature request. I'll open one now.

**Comment by iterion** [comment]
OK, thanks, I should note that new features are unlikely to be added. The goal is to replace this project with a new community driven effort found here: https://github.com/kubernetes-incubator/external-dns

It's possible that the feature you're requesting is already a planned/implemented goal of that project. I'm still not quite sure what you're advocating for though.

**Comment by iterion** [comment]
I think perhaps the `Ingress` type is what you're looking for? If so, it is indeed supported by the external-dns project above.

**Comment by jangrewe** [comment]
Oh, didn't see that one yet, thanks for the hint!

**Comment by iterion** [comment]
No problem. I'll be officially deprecating this repo once external-dns is in a more stable state. But, I'd highly recommend checking out what has been accomplished so far. Also, if you'd like to use Ingress today you can check out https://github.com/zalando-incubator/mate. However, the plan is also to replace that project with external-dns.

**Comment by foobarto** [comment]
That looks great. Will keep an eye on it thanks!
