### ISSUE TITLE
unable to contact the API server

### ISSUE THREAD

**Issue by spyrosg** [wearemolecule/route53-kubernetes#6]
I've been trying to run the service on a kubernetes cluster (v1.2.4) but it seems to be failing: 

Looking in the logs I get the following:

```
I0601 13:37:39.698519       1 service_listener.go:26] Route53 Update Service
I0601 13:37:39.699695       1 service_listener.go:64] Connected to kubernetes @ https://10.0.0.1:443
I0601 13:37:39.699822       1 service_listener.go:93] Starting Service Polling every 30s
F0601 13:37:39.721357       1 service_listener.go:97] Failed to list pods: the server has asked for the client to provide credentials (get services)
```

So it seems that the service is unable to contact the k8s API server.

Using the same credentials I am able to contact the API server from an external node.

**Comment by osxi** [comment]
@spyrosg can you provide your definitions?

**Comment by osxi** [comment]
Please re-open if this is still an issue.

**Comment by luohoufu** [comment]
i also get the error.
[kube-error.txt](https://github.com/wearemolecule/route53-kubernetes/files/583576/kube-error.txt)

**Comment by iterion** [comment]
@luohoufu I don't see route53-kubernetes anywhere in those logs, perhaps you posted your issue in the wrong place. Also, please be careful with the things you post, it appears that text file contains credentials to your cluster.
