### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by developerinlondon** [wearemolecule/route53-kubernetes#7]
any ideas how i can install it to my existing kubernetes stack?

**Comment by developerinlondon** [comment]
@iterion any updates on installation instructions?

**Comment by osxi** [comment]
@developerinlondon I should have these instructions merged in shortly. Feel free to check out the PR (https://github.com/wearemolecule/route53-kubernetes/issues/8) and ask any questions here.

**Comment by osxi** [comment]
I'm going to go ahead and close this. Please open a new issue if you have additional questions.
